//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheFund.AtidsXe.GraphQL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheFund.AtidsXe.GraphQL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acreage Government lot legals associated with this search Id.
        /// </summary>
        internal static string Acreage_Government_lot_legals_associated_with_this_search_Id {
            get {
                return ResourceManager.GetString("Acreage_Government_lot_legals_associated_with_this_search_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information about this title event.
        /// </summary>
        internal static string Additional_information_about_this_title_event {
            get {
                return ResourceManager.GetString("Additional_information_about_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch location for this file reference.
        /// </summary>
        internal static string Branch_location_for_this_file_reference {
            get {
                return ResourceManager.GetString("Branch_location_for_this_file_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification range types from this official record document.
        /// </summary>
        internal static string Certification_range_types_from_this_official_record_document {
            get {
                return ResourceManager.GetString("Certification_range_types_from_this_official_record_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification range types to this official record document.
        /// </summary>
        internal static string Certification_range_types_to_this_official_record_document {
            get {
                return ResourceManager.GetString("Certification_range_types_to_this_official_record_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain of title items associated with chain of title category.
        /// </summary>
        internal static string Chain_of_title_items_associated_with_chain_of_title_category {
            get {
                return ResourceManager.GetString("Chain_of_title_items_associated_with_chain_of_title_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain of title items for this title event.
        /// </summary>
        internal static string Chain_of_title_items_for_this_title_event {
            get {
                return ResourceManager.GetString("Chain_of_title_items_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain of title notes.
        /// </summary>
        internal static string Chain_of_title_notes {
            get {
                return ResourceManager.GetString("Chain_of_title_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain of title searches.
        /// </summary>
        internal static string Chain_of_title_searches {
            get {
                return ResourceManager.GetString("Chain_of_title_searches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain of titles associated with this file reference.
        /// </summary>
        internal static string Chain_of_titles_associated_with_this_file_reference {
            get {
                return ResourceManager.GetString("Chain_of_titles_associated_with_this_file_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current examination status type for this title event.
        /// </summary>
        internal static string Current_examination_status_type_for_this_title_event {
            get {
                return ResourceManager.GetString("Current_examination_status_type_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File reference associated with this chain of title.
        /// </summary>
        internal static string File_reference_associated_with_this_chain_of_title {
            get {
                return ResourceManager.GetString("File_reference_associated_with_this_chain_of_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File reference Id.
        /// </summary>
        internal static string File_reference_Id {
            get {
                return ResourceManager.GetString("File_reference_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File reference notes associated with this file reference.
        /// </summary>
        internal static string File_reference_notes_associated_with_this_file_reference {
            get {
                return ResourceManager.GetString("File_reference_notes_associated_with_this_file_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File reference query.
        /// </summary>
        internal static string File_reference_query {
            get {
                return ResourceManager.GetString("File_reference_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File status for this file reference.
        /// </summary>
        internal static string File_status_for_this_file_reference {
            get {
                return ResourceManager.GetString("File_status_for_this_file_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic locale for this file reference.
        /// </summary>
        internal static string Geographic_locale_for_this_file_reference {
            get {
                return ResourceManager.GetString("Geographic_locale_for_this_file_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets a single title event record by id.
        /// </summary>
        internal static string Gets_a_single_title_event_record_by_id {
            get {
                return ResourceManager.GetString("Gets_a_single_title_event_record_by_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government lot legal associated with this acreage government lot legal.
        /// </summary>
        internal static string Government_lot_legal_associated_with_this_acreage_government_lot_legal {
            get {
                return ResourceManager.GetString("Government_lot_legal_associated_with_this_acreage_government_lot_legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes mortgagee short form.
        /// </summary>
        internal static string InitializePrimitiveTypes_Includes_mortgagee_short_form {
            get {
                return ResourceManager.GetString("InitializePrimitiveTypes_Includes_mortgagee_short_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this search hidden.
        /// </summary>
        internal static string InitializePrimitiveTypes_Is_this_search_hidden {
            get {
                return ResourceManager.GetString("InitializePrimitiveTypes_Is_this_search_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this a temporary file.
        /// </summary>
        internal static string Is_this_a_temporary_file {
            get {
                return ResourceManager.GetString("Is_this_a_temporary_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lrs search.
        /// </summary>
        internal static string Lrs_search {
            get {
                return ResourceManager.GetString("Lrs_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage title event for this title event.
        /// </summary>
        internal static string Mortgage_title_event_for_this_title_event {
            get {
                return ResourceManager.GetString("Mortgage_title_event_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name search list items for this title event.
        /// </summary>
        internal static string Name_search_list_items_for_this_title_event {
            get {
                return ResourceManager.GetString("Name_search_list_items_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official record status for this title event.
        /// </summary>
        internal static string Official_record_status_for_this_title_event {
            get {
                return ResourceManager.GetString("Official_record_status_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original examination status type for this title event.
        /// </summary>
        internal static string Original_examination_status_type_for_this_title_event {
            get {
                return ResourceManager.GetString("Original_examination_status_type_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries for the Title Event table.
        /// </summary>
        internal static string Queries_for_the_Title_Event_table {
            get {
                return ResourceManager.GetString("Queries_for_the_Title_Event_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search associated with this acreage government lot legal.
        /// </summary>
        internal static string Search_associated_with_this_acreage_government_lot_legal {
            get {
                return ResourceManager.GetString("Search_associated_with_this_acreage_government_lot_legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches associated with this file reference.
        /// </summary>
        internal static string Searches_associated_with_this_file_reference {
            get {
                return ResourceManager.GetString("Searches_associated_with_this_file_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chain of title associated with this chain of title item.
        /// </summary>
        internal static string The_chain_of_title_associated_with_this_chain_of_title_item {
            get {
                return ResourceManager.GetString("The_chain_of_title_associated_with_this_chain_of_title_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chain of title category associated with this chain of title item.
        /// </summary>
        internal static string The_chain_of_title_category_associated_with_this_chain_of_title_item {
            get {
                return ResourceManager.GetString("The_chain_of_title_category_associated_with_this_chain_of_title_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file reference Id.
        /// </summary>
        internal static string The_file_reference_Id {
            get {
                return ResourceManager.GetString("The_file_reference_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting title event associated with this chain of title item.
        /// </summary>
        internal static string The_starting_title_event_associated_with_this_chain_of_title_item {
            get {
                return ResourceManager.GetString("The_starting_title_event_associated_with_this_chain_of_title_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag associated with this title event.
        /// </summary>
        internal static string The_tag_associated_with_this_title_event {
            get {
                return ResourceManager.GetString("The_tag_associated_with_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title event associated with this chain of title item.
        /// </summary>
        internal static string The_title_event_associated_with_this_chain_of_title_item {
            get {
                return ResourceManager.GetString("The_title_event_associated_with_this_chain_of_title_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user id of the user who modified this chain of title item.
        /// </summary>
        internal static string The_user_id_of_the_user_who_modified_this_chain_of_title_item {
            get {
                return ResourceManager.GetString("The_user_id_of_the_user_who_modified_this_chain_of_title_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title event government legal entity mql types for this title event.
        /// </summary>
        internal static string Title_event_government_legal_entity_mql_types_for_this_title_event {
            get {
                return ResourceManager.GetString("Title_event_government_legal_entity_mql_types_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title event government lot legal mql types for this title event.
        /// </summary>
        internal static string Title_event_government_lot_legal_mql_types_for_this_title_event {
            get {
                return ResourceManager.GetString("Title_event_government_lot_legal_mql_types_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title event note types for this title event.
        /// </summary>
        internal static string Title_event_note_types_for_this_title_event {
            get {
                return ResourceManager.GetString("Title_event_note_types_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title event order tracking types for this title event.
        /// </summary>
        internal static string Title_event_order_tracking_types_for_this_title_event {
            get {
                return ResourceManager.GetString("Title_event_order_tracking_types_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title event party types for this title event.
        /// </summary>
        internal static string Title_event_party_types_for_this_title_event {
            get {
                return ResourceManager.GetString("Title_event_party_types_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title event platted legal mql types for this title event.
        /// </summary>
        internal static string Title_event_platted_legal_mql_types_for_this_title_event {
            get {
                return ResourceManager.GetString("Title_event_platted_legal_mql_types_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title event search types for this title event.
        /// </summary>
        internal static string Title_event_search_types_for_this_title_event {
            get {
                return ResourceManager.GetString("Title_event_search_types_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title event searches associated with this search Id.
        /// </summary>
        internal static string Title_event_searches_associated_with_this_search_Id {
            get {
                return ResourceManager.GetString("Title_event_searches_associated_with_this_search_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title event section legal mql types for this title event.
        /// </summary>
        internal static string Title_event_section_legal_mql_types_for_this_title_event {
            get {
                return ResourceManager.GetString("Title_event_section_legal_mql_types_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title event type for this title event.
        /// </summary>
        internal static string Title_event_type_for_this_title_event {
            get {
                return ResourceManager.GetString("Title_event_type_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title search origination for this file reference.
        /// </summary>
        internal static string Title_search_origination_for_this_file_reference {
            get {
                return ResourceManager.GetString("Title_search_origination_for_this_file_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title search origination types for this title event.
        /// </summary>
        internal static string Title_search_origination_types_for_this_title_event {
            get {
                return ResourceManager.GetString("Title_search_origination_types_for_this_title_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet for this file reference.
        /// </summary>
        internal static string Worksheet_for_this_file_reference {
            get {
                return ResourceManager.GetString("Worksheet_for_this_file_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet item types for this title event.
        /// </summary>
        internal static string Worksheet_item_types_for_this_title_event {
            get {
                return ResourceManager.GetString("Worksheet_item_types_for_this_title_event", resourceCulture);
            }
        }
    }
}
